# Generated by Django 5.2.3 on 2025-07-16 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ledgerentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_name', models.CharField(max_length=255)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('group', models.CharField(blank=True, max_length=255)),
                ('raw_balance', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='accounts.client')),
            ],
        ),
    ]
