# Generated by Django 5.2.3 on 2025-07-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallytransaction',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
